### ISSUE TITLE
Add a separator between story title and author name in the <title> tag

### ISSUE THREAD

**Issue by vajra** [strangehorizons/website#11]
Without a separator it looks odd when they run together. A dash or a "by" would work.

**Comment by dreamertim** [comment]
@vajra I'm seeing:

`<title>Strange Horizons - I Learn the Police Once Beat My Uncle for Smudging By Halee Kirkwood</title>`

There are similar outputs in the other stories for this week's stories.

Do you have links for where you are seeing this issue?

**Comment by vajra** [comment]
It seems to happen on any post where the new bylines aren't set. E.g. 

- http://strangehorizons.com/fiction/blood-blood-part-1-of-2/
- http://strangehorizons.com/fiction/this-is-a-letter-to-my-son/
- http://strangehorizons.com/fiction/difference-of-opinion/
