### ISSUE TITLE
titles now have "by" suffixes for pages that shouldn't have them

### ISSUE THREAD

**Issue by vajra** [strangehorizons/website#12]
SH main page: "Strange Horizons - A Magazine of Speculative Fiction By Niall Harrison"
Samovar main page: "Samovar - By Sarah"

And about, submit pages like so:
Strange Horizons - About By Strange Horizons
Strange Horizons - Submit By Strange Horizons
Samovar - About By Strange Horizons
Samovar - Submit By Strange Horizons

And so on.

**Comment by dreamertim** [comment]
I believe this was fixed in 74d5f8a. If it is still broken, please reply and I'll look again.
